import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { dark } from "@clerk/themes";
import { ClerkLoaded, ClerkLoading, ClerkProvider} from "@clerk/nextjs";
import { Providers } from "./provider"; // Import the new Providers component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark}}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Providers> {/* Move providers here */}
            <ClerkLoading>
              <div className="flex items-center justify-center h-screen bg-gray-900">
                <div className="text-white text-2xl font-bold">Loading...</div>
              </div>
            </ClerkLoading>
            <ClerkLoaded>
              <Navbar />  
            <main>{children}</main>
            </ClerkLoaded>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
